<a href="https://colab.research.google.com/github/ChoiDae1/Machine-DeepLearing_Study/blob/main/%EC%95%99%EC%83%81%EB%B8%94_%ED%95%99%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
wine= pd.read_csv('https://bit.ly/wine-date')
wine_input = wine[['alcohol', 'sugar', 'pH' ]].to_numpy()
wine_target = wine['class'].to_numpy()
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(wine_input,wine_target,random_state=42,test_size = 0.2)
from sklearn.model_selection import cross_validate
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(n_jobs=-1, random_state = 42)
scores = cross_validate(rf, train_input, train_target, return_train_score= True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
rf.fit(train_input, train_target)
print(rf.feature_importances_)
rf = RandomForestClassifier(oob_score=True, n_jobs=-1, random_state=42)
rf.fit(train_input, train_target)
print(rf.oob_score_)

0.9973541965122431 0.8905151032797809
[0.23167441 0.50039841 0.26792718]
0.8934000384837406


In [ ]:
import numpy as np
import pandas as pd
wine= pd.read_csv('https://bit.ly/wine-date')
wine_input = wine[['alcohol', 'sugar', 'pH' ]].to_numpy()
wine_target = wine['class'].to_numpy()
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(wine_input,wine_target,random_state=42,test_size = 0.2)
from sklearn.model_selection import cross_validate
from sklearn.ensemble import ExtraTreesClassifier
et = ExtraTreesClassifier(n_jobs=-1, random_state=42)
scores = cross_validate(et, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
et.fit(train_input, train_target)
print(et.feature_importances_)

0.9974503966084433 0.8887848893166506
[0.20183568 0.52242907 0.27573525]


In [ ]:
import numpy as np
import pandas as pd
wine= pd.read_csv('https://bit.ly/wine-date')
wine_input = wine[['alcohol', 'sugar', 'pH' ]].to_numpy()
wine_target = wine['class'].to_numpy()
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(wine_input,wine_target,random_state=42,test_size = 0.2)
from sklearn.model_selection import cross_validate
from sklearn.ensemble import GradientBoostingClassifier
gb = GradientBoostingClassifier(random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
gb = GradientBoostingClassifier(random_state=42,n_estimators=500, learning_rate=0.2)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
gb.fit(train_input, train_target)
print(gb.feature_importances_)

0.8881086892152563 0.8720430147331015
0.9464595437171814 0.8780082549788999
[0.15872278 0.68010884 0.16116839]


In [ ]:
import numpy as np
import pandas as pd
wine= pd.read_csv('https://bit.ly/wine-date')
wine_input = wine[['alcohol', 'sugar', 'pH' ]].to_numpy()
wine_target = wine['class'].to_numpy()
from sklearn.model_selection import train_test_split
train_input,test_input,train_target,test_target = train_test_split(wine_input,wine_target,random_state=42,test_size = 0.2)
from sklearn.model_selection import cross_validate
from sklearn.experimental import enable_hist_gradient_boosting
from sklearn.ensemble import HistGradientBoostingClassifier
hgb = HistGradientBoostingClassifier(random_state=42)
scores = cross_validate(hgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))
hgb.fit(train_input,train_target)
print(hgb.score(test_input, test_target))

from xgboost import XGBClassifier
xgb = XGBClassifier(tree_method='hist', random_state=42)
scores = cross_validate(xgb, train_input, train_target, return_train_score=True)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))

from lightgbm import LGBMClassifier
lgb = LGBMClassifier(random_state=42)
scores = cross_validate(lgb,train_input,train_target,return_train_score=True, n_jobs=-1)
print(np.mean(scores['train_score']),np.mean(scores['test_score']))



0.9321723946453317 0.8801241948619236
0.8723076923076923
0.8824322471423747 0.8726214185237284
0.9338079582727165 0.8789710890649293
